"use client";

import {
  Box,
  Container,
  Divider,
  Flex,
  Grid,
  GridItem,
} from "@/components/chakra-ui/react";
import Provider from "@/components/Provider";
import { Noto_Sans_JP } from "next/font/google";

const font = Noto_Sans_JP({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body>
        <Box
          as="body"
          fontFamily={font.style.fontFamily}
          fontWeight={font.style.fontWeight}
          fontStyle={font.style.fontStyle}
        >
          <Provider>
            <Flex direction="column" h="100dvh" w="100dvw">
              <Grid
                as="header"
                h="16"
                flex="none"
                placeItems="center"
                fontWeight="bold"
              >
                <GridItem>Header</GridItem>
              </Grid>
              <Divider />
              <Container as="main" flexGrow={1} display="grid">
                {children}
              </Container>
              <Divider />
              <Grid
                as="footer"
                h="16"
                flex="none"
                placeItems="center"
                fontWeight="bold"
              >
                <GridItem>Footer</GridItem>
              </Grid>
            </Flex>
          </Provider>
        </Box>
      </body>
    </html>
  );
}
